### ISSUE TITLE
Implement request rate limiting for the Spoonacular API

### ISSUE THREAD

**Issue by nashirj** [COP4331-LargeGroupProject-Fall22/backend#26]
Since we're using [Spoonacular](https://spoonacular.com/food-api), we need to be careful about users spamming requests and using all of our quota (free student plan has 5000 requests/day).

We plan to accomplish this by storing the number of requests that have been made to Spoonacular so far each day (in MongoDB) and resetting this value daily using a JS callback. One thing we should consider is per-user rate limiting, since we don't want to penalize all users if one user makes a huge amount of requests, but this can be something we consider later if needed.

**Comment by mplekunov** [comment]
implemented on the branch add-client-server-interface-for-recipeAPI

**Comment by mplekunov** [comment]
I accomplished it differently though, you can look at the the code on that branch, specifically SpoonacularAPIUtils folder. Essentially, this requirement is related to all API classes that use SpoonacularAPI. As such, it makes sense to create a base class with all similar functionalities that all API classes should have and then extend API classes related to SpoonacularAPI with that base class.

**Comment by nashirj** [comment]
Sounds good, when you make a PR, please link this issue
