### ISSUE TITLE
Create data model and corresponding ERD

### ISSUE THREAD

**Issue by nashirj** [COP4331-LargeGroupProject-Fall22/backend#4]

**Comment by nashirj** [comment]
Resources:
- [Discussion on relational model](https://towardsdatascience.com/automating-sunday-meal-preps-using-sqlite-relational-databases-and-python-c85821099ca8)
- [Intro to data modeling](http://www.gpcdata.com/downloads/normalizationgpgonaccess.pdf)
- [Naming conventions](https://www.access-diva.com/d1.html)
- [Modeling human relationships](http://allenbrowne.com/AppHuman.html)
- [Sample ERD 1](https://www.chegg.com/homework-help/questions-and-answers/sql-queries-attached-er-diagram-database-also-use-imaginary-recipe-database-schema-recipe--q24253967)
- [Sample ERD 2](https://www.chegg.com/homework-help/questions-and-answers/want-create-database-recipes-recipe-name-list-ingredients-list-steps-following-conceptual--q28293176)
- [Sample ERD 3](https://stackoverflow.com/questions/5133248/recipe-database-design-advice)
- [Sample ERD 4](https://user-images.githubusercontent.com/20624069/196005201-0e6512fd-1f49-461c-a9fc-f9573a1fb47a.png)
- [Sample ERD 5](https://www.access-diva.com/dm15.html)
- [Sample ERD 5](https://www.access-diva.com/dm17.html)

**Comment by nashirj** [comment]
@mplekunov every time you update DataModel.puml, can you please render and add it as an image to the README.md?

**Comment by mplekunov** [comment]
I will
