### ISSUE TITLE
Expiration Date on duplicate items

### ISSUE THREAD

**Issue by mplekunov** [COP4331-LargeGroupProject-Fall22/backend#48]
Right now item uniqueness is guaranteed by their "id". ID is the id of an item that we get from IFoodAPI interface. Since we don't store specific items but rather their general representation (e.g. not FairLife Milk but just "Milk") we can go with that approach for a long while. 

Now, when it comes to the expiration date. If we are going with the approach above, I can give you two ways of adding this feature.

1. We only store one item and use the earliest expiration date available (assuming we don't have multiple items)
2. Assign to Food items some other identification which will allow us to base uniqueness of food items not on the id given to us from IFoodAPI but rather from this new identification. 

In case 2 we will just show items as it is because they are all unique essentially. (I'm all for approach 2)

**Comment by nashirj** [comment]
I think we should store all expiration dates until an item is removed/used up, but only display the soonest expiration date until it passes, and then display the next soonest. If that corresponds to approach 2 then I agree
